const { google } = require('googleapis');

/**
 * Zylron Google Calendar Orchestration Service
 * Manage schedules and meetings via AI commands
 */
const calendarAction = async (action, details = {}) => {
    const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;

    if (!refreshToken || !clientId || !clientSecret) {
        console.warn('⚠️ Google Calendar credentials missing.');
        return { success: false, message: 'Calendar not linked. Please configure API keys.' };
    }

    const oauth2Client = new google.auth.OAuth2(clientId, clientSecret);
    oauth2Client.setCredentials({ refresh_token: refreshToken });
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client });

    try {
        switch (action) {
            case 'list':
                const response = await calendar.events.list({
                    calendarId: 'primary',
                    timeMin: new Date().toISOString(),
                    maxResults: 5,
                    singleEvents: true,
                    orderBy: 'startTime',
                });
                const events = response.data.items;
                return { success: true, data: events, message: 'Events fetched successfully' };

            case 'create':
                const event = {
                    summary: details.title || 'Zylron Neural Meeting',
                    description: details.description || 'Generated by Zylron AI',
                    start: { dateTime: details.start || new Date().toISOString() },
                    end: { dateTime: details.end || new Date(Date.now() + 3600000).toISOString() },
                };
                await calendar.events.insert({ calendarId: 'primary', resource: event });
                return { success: true, message: 'Event created in Google Calendar' };

            default:
                return { success: false, message: 'Unknown calendar action' };
        }
    } catch (error) {
        console.error('📅 Calendar Service Error:', error.message);
        return { success: false, message: 'Calendar sync failed. Check API permissions.' };
    }
};

module.exports = { calendarAction };
