import React from 'react';
import SEO from '../../components/SEO';

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-slate-950 text-slate-300 py-24 px-4 font-sans">
            <SEO title="Terms of Service" canonical="/terms-of-service" />
            <div className="max-w-3xl mx-auto bg-slate-900 border border-slate-800 p-8 md:p-12 rounded-3xl">
                <h1 className="text-4xl font-black text-white mb-4">Terms of Service</h1>
                <p className="text-slate-500 mb-12">Last Updated: October 24, 2026</p>

                <div className="space-y-8">
                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                        <p className="leading-relaxed">
                            By accessing and using Zylron (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
                        </p>
                    </section>
                    
                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
                        <p className="leading-relaxed">
                            Zylron provides AI-driven educational and computational tools. We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without notice.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">3. User Conduct</h2>
                        <p className="leading-relaxed mb-4">
                            You agree not to use the Service to:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-slate-400">
                            <li>Violate any local, state, national, or international law.</li>
                            <li>Attempt to reverse engineer the Zylron Neural Engine.</li>
                            <li>Exceed automated API rate limits intentionally.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
                        <p className="leading-relaxed">
                            All content generated by Zylron is provided for educational purposes. The underlying AI models, UI/UX designs, and source code are the intellectual property of Zylron Inc.
                        </p>
                    </section>
                </div>
                
                <footer className="mt-20 pt-8 border-t border-gray-100 dark:border-gray-900 text-center text-[10px] text-gray-400 uppercase tracking-widest flex flex-col items-center gap-4">
                    <p>© 2026 Zylron AI Ecosystem • Built by Thirumalai • All Rights Reserved</p>
                    <p className="text-[9px] max-w-lg normal-case tracking-normal opacity-60">
                        Disclaimer: Zylron AI is an independent neural workspace platform designed for productivity. We are not associated, affiliated, or partnered with Zylon enterprise private LLM software platforms.
                    </p>
                </footer>
            </div>
        </div>
    );
}
